### ISSUE TITLE
Chase car on map issue

### ISSUE THREAD

**Issue by geftactics** [PiInTheSky/LCARS#6]
It looks like when the upload car location feature is enabled, it is posting to spacenear.us, but this domains registration appears to have lapsed.

https://github.com/PiInTheSky/LCARS/blob/0234c41812f3c197195f15f66e74bde6cf2ff009/lcars.py#L1462

Is there another endpoint that will allow post onto habitat tracker?

**Comment by PiInTheSky** [comment]
Oh great.  I'll check and I'll let you know.  That will affect several of
my apps.

Dave

**Comment by PiInTheSky** [comment]
Fixed.  spacenear.us is no more, and the relevant PHP code is now at http://legacy-snus.habhub.org/tracker/track.php
